
changeLogFile=main-changelog_pg_recover.xml
liquibase.command.url=jdbc:postgresql://10.7.118.211:5432/rshb_sofr_upgrade


# liquibase.command.username: RSHB_SOFR_TEST
# liquibase.command.password: RSHB_SOFR_TEST

liquibase.command.username: rshb_sofr
liquibase.command.password: rshbSOFR123#

# Valid values, from least amount of logging to most, are:
#   OFF, ERROR, WARN, INFO, DEBUG, TRACE, ALL
# logLevel: DEBUG

# The logFile property controls where logging messages are sent. If this is not set, then logging messages are
# displayed on the console. If this is set, then messages will be sent to a file with the given name.
# logFile: liquibase.log

liquibase.hub.mode=off