
changeLogFile=main-changelog.xml
liquibase.command.url=jdbc:oracle:thin:@10.7.118.141:1521:sofr


# liquibase.command.username: RSHB_SOFR_TEST
# liquibase.command.password: RSHB_SOFR_TEST

liquibase.command.username: RSHB_SOFR_DEBUG
liquibase.command.password: RSHB_SOFR_DEBUG

# Valid values, from least amount of logging to most, are:
#   OFF, ERROR, WARN, INFO, DEBUG, TRACE, ALL
# logLevel: DEBUG

# The logFile property controls where logging messages are sent. If this is not set, then logging messages are
# displayed on the console. If this is set, then messages will be sent to a file with the given name.
# logFile: liquibase.log

liquibase.hub.mode=off